name: "1 SYFT, COSIGN"
on:
  push:
    branches: [ "3.6.0_release" ]
  pull_request:
    branches: [ "3.6.0_release" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing SBOM
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .

    - name: Generate SBOM
      run: |
        ./syft . -o spdx-tag-value=sbom-syft.spdx
        ls -al

    - name: Installing cosign
      uses: sigstore/cosign-installer@main

    - name: generate cosign key   
      run: |
        cosign generate-key-pair 
        cosign sign --key $GITHUB_WORKSPACE/cosign.key $GITHUB_WORKSPACE/sbom-syft.spdx
