name: "ANCHORE SYFT SBOM"
on:
  push:
    branches: [ "3.6.0_release" ]
  pull_request:
    branches: [ "3.6.0_release" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing SBOM
      run: |
        curl -o sbom.tar.gz https://github.com/opensbom-generator/spdx-sbom-generator/releases/download/v0.0.15/spdx-sbom-generator-v0.0.15-linux-amd64.tar.gz
        tar xvzf sbom.tar.gz

    - name: Generate SBOM
      run: |
        ls

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: SBOMOUTPUT/_manifest/spdx_2.2/manifest.spdx.json
        if-no-files-found: error