name: "Criticality Score"
on:
  push:
    branches: [ "3.6.0-CriticalityScore" ]
  pull_request:
    branches: [ "3.6.0-CriticalityScore" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Installing criticality score
      run: |
        go install github.com/ossf/criticality_score/cmd/criticality_score@latest

    - name: Generate criticality score
      run: |
        export GITHUB_AUTH_TOKEN=${{ secrets.AUTH_KEY }}
        criticality_score -gcp-project-id=719083236 https://github.com/sand-hya/kafka
