name: "criticality score with go"
on:
  push:
    branches: 
      - 3.6.0-CriticalityScore
  
  workflow_dispatch:
      inputs:
          github_auth_token:
            description: 'github auth token'
            required: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Installing criticality score
      run: |
        go install github.com/ossf/criticality_score/cmd/criticality_score@latest

    - name: Generate criticality score
      run: |
        export GITHUB_AUTH_TOKEN=$INPUT_TOKEN
        criticality_score --help
        criticality_score github.com/sand-hya/kafka
      env:
        INPUT_TOKEN: ${{ github.event.inputs.github_auth_token }}
