name: "criticality score with pip"
on:
  push:
    branches: 
      - 3.6.0-CriticalityScore
  
  workflow_dispatch:
      inputs:
          github_auth_token:
            description: 'github auth token'
            required: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Installing python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installing criticality score
      run: |
        pip install criticality_score

    - name: Generate criticality score
      run: |
        export GITHUB_AUTH_TOKEN=$INPUT_TOKEN
        echo ${{ secrets.GITHUB_TOKEN }}
        criticality_score --help
        criticality_score --repo github.com/${{ github.repository }}
      env:
        INPUT_TOKEN: ${{ github.event.inputs.github_auth_token }}
