name: "SBOM"
on:
  push:
    branches: [ "3.6.0_release" ]
  pull_request:
    branches: [ "3.6.0_release" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin', 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Installing SBOM
      run: |
        curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod 777 sbom-tool

    - name: Generate SBOM
      run: |
        sbom-tool-linux-x64 generate -b kafka/ -bc kafka/ -pn kafka -pv 3.6.0 -ps wipro -nsb https://github.com/apache/kafka

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.spdx