name: "ANCHORE SYFT"
on:
  push:
    branches: [ "3.6.0_release" ]
  pull_request:
    branches: [ "3.6.0_release" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing SBOM
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .

    - name: Generate SBOM
      run: |
        ./syft --help

    #- name: Upload SBOM artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: sbom
    #    path: SBOMOUTPUT/_manifest/spdx_2.2/manifest.spdx.json
    #    if-no-files-found: error
